/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1ForecastRouteImport } from './routes/api/v1/forecast'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1MetricsRouteImport } from './routes/api/v1/metrics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ForecastRoute = ApiV1ForecastRouteImport.update({
  id: '/api/v1/forecast',
  path: '/api/v1/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MetricsRoute = ApiV1MetricsRouteImport.update({
  id: '/api/v1/metrics',
  path: '/api/v1/metrics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1/forecast': typeof ApiV1ForecastRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/metrics': typeof ApiV1MetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1/forecast': typeof ApiV1ForecastRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/metrics': typeof ApiV1MetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1/forecast': typeof ApiV1ForecastRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/metrics': typeof ApiV1MetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/v1/forecast' | '/api/v1/health' | '/api/v1/metrics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/v1/forecast' | '/api/v1/health' | '/api/v1/metrics'
  id:
    '__root__' | '/' | '/api/v1/forecast' | '/api/v1/health' | '/api/v1/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1ForecastRoute: typeof ApiV1ForecastRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1MetricsRoute: typeof ApiV1MetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/forecast': {
      id: '/api/v1/forecast'
      path: '/api/v1/forecast'
      fullPath: '/api/v1/forecast'
      preLoaderRoute: typeof ApiV1ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/metrics': {
      id: '/api/v1/metrics'
      path: '/api/v1/metrics'
      fullPath: '/api/v1/metrics'
      preLoaderRoute: typeof ApiV1MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1ForecastRoute: ApiV1ForecastRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1MetricsRoute: ApiV1MetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
